#!/bin/bash

USAGE="
cccp - Crowd Control Copy

Usage:
    $(basename $0) <source> <destination>
"

LOCKFILE=""
on_die()
{
	echo "Dying..."
    if [ ! -z "$LOCKFILE" ]
    then
        rm "$LOCKFILE"
    fi
	exit 1
}

trap 'on_die' HUP INT TERM

if [ $# -ne 2 ]
then
    echo "$USAGE"
    exit 1
fi

SRCDIR=$(dirname "$1")
LOCKDIR=$SRCDIR/.cccp
mkdir -p "$LOCKDIR"
DSTDIR=$(dirname "$2")

LOCKS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name .cccp-lock-* | wc -l)
MAXLOCKS=10

echo "Waiting for free lock..."

while [ $LOCKS -ge $MAXLOCKS ]
do
    sleep $(( $RANDOM % 1200 ))
    LOCKS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name .cccp-lock-* | wc -l)
done

echo "Starting copy operation..."

LOCKFILE="$LOCKDIR/.cccp-lock-$(hostname)-$RANDOM"
touch $LOCKFILE
cp -v $1 $2
rm $LOCKFILE

echo "Done."
