#!/bin/bash

USAGE="
cccp - Crowd Control Copy

Usage:
    $(basename $0) <source> <destination>
"

LOCKFILE=""
TICKETFILE=""
on_die()
{
	echo "Dying..."
    if [ ! -z "$LOCKFILE" ]
    then
        rm "$LOCKFILE"
    fi
    if [ ! -z "$TICKETFILE" ]
    then
        rm "$TICKETFILE"
    fi
	exit 1
}

trap 'on_die' HUP INT TERM

if [ $# -ne 2 ]
then
    echo "$USAGE"
    exit 1
fi

SRCDIR=$(dirname "$1")
LOCKDIR=$SRCDIR/.cccp
mkdir -p "$LOCKDIR"
DSTDIR=$(dirname "$2")

# Broadcast that we would like to copy a file
TICKETFILE="$LOCKDIR/cccp-ticket-$(hostname)-$RANDOM"
touch "$TICKETFILE"

sleep $(( 1 + ($RANDOM % 10) ))

# Check how many other processes are copying or want to copy
LOCKS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name cccp-lock-* | wc -l)
TICKETS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name cccp-ticket-* | wc -l)
MAXLOCKS=10

echo "Waiting for free lock..."

while [ $LOCKS -ge $MAXLOCKS ]
do
    # If we cannot copy yet, wait an amount of time proportional to the number of waiting processes
    sleep $(( 5 + $RANDOM % ($TICKETS * 60) ))
    # Make sure the ticket is still there and fresh
    touch "$TICKETFILE"
    LOCKS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name cccp-lock-* | wc -l)
    TICKETS=$(find $LOCKDIR -maxdepth 1 -mmin -360 -name cccp-ticket-* | wc -l)
done

echo "Starting copy operation..."

LOCKFILE="$LOCKDIR/cccp-lock-$(hostname)-$RANDOM"
touch "$LOCKFILE"
cp -v "$1" "$2"
rm "$LOCKFILE"
rm "$TICKETFILE"

echo "Done."
